import localFont from "next/font/local";
import "./globals.css";

const vazir = localFont({
  src: [
    {
      path: "./fonts/Vazir-Black-UI.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Vazir-Bold-UI.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Vazir-Medium-UI.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Vazir-Regular-UI.woff",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa-IR">
      <body
        className={` ${vazir.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
